maykinmedia/sdg-invoervoorziening

Makefile
src/openapi.yaml
src/sdg/api/filters/__init__.py
src/sdg/api/filters/constants.py
src/sdg/api/filters/filtersets.py
src/sdg/api/tests/test_filters.py

Fixes #28
_______
**Changes**
- Add filter for product aanwezig
- Add tests for product aanwezig filter

Product aanwezig filter

---

src/sdg/api/serializers/core.py
src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_api.py
src/sdg/api/views/core.py
src/sdg/api/views/organisaties.py
src/sdg/api/views/producten.py
src/sdg/producten/models/product.py

Fixes #248
Apart from optimizations I added 2 fields in the API: `catalogus.organisatie`, and `product.publicatieDatum` (mentioned in #251)

Optimize API queries

---

src/sdg/core/admin/catalogus.py
src/sdg/core/admin/logius.py
src/sdg/producten/admin/product.py

Straightforward query improvements to make the admin workable with many products.

Improve admin performance.

---

.github/workflows/ci.yml

added downstream deployment to ci run.

added downstream deploy to workflow

---

.github/workflows/ci.yml
Dockerfile
requirements/setuptools.txt
src/openapi.yaml
src/sdg/api/views/producten.py

Fixes #271 
**Changes**
- Added OAS checks
- Split Docker build from Docker push
- Moved CD trigger to its own step

Various CI changes

---

.github/workflows/ci.yml

fix trigger deploy var

---

package-lock.json
package.json
src/sdg/core/models/managers.py
src/sdg/js/components/diff.js
src/sdg/js/components/edit.js
src/sdg/js/components/index.js
src/sdg/js/components/reference.js
src/sdg/producten/views/product.py
src/sdg/scss/components/_diff.scss
src/sdg/scss/components/_form.scss
src/sdg/scss/components/_index.scss
src/sdg/scss/components/_reference.scss
src/sdg/scss/components/_tabs.scss
src/sdg/templates/forms/table_field.html
src/sdg/templates/forms/table_row.html
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/edit.html

Fixes #215
_______
**Changes**
- Added text-diff to js packages
- Added diff button to standard text preview
- Added dynamic legend to differ with the following format "{version} ({publication date})"

CMS standard text diff tool

---

src/sdg/organisaties/views/mixins.py
src/sdg/templates/organisaties/roles/list.html

Fixes #265
_______
**Changes**
- Hide add button for non-managers

Hide add button for non-managers

---

src/sdg/accounts/mixins.py
src/sdg/core/models/managers.py
src/sdg/core/tests/factories/logius.py
src/sdg/organisaties/models.py
src/sdg/organisaties/views/catalogi.py

**Changes**
- Refactored CatalogListView to use proper ProductenCatalogus model and ListView
- Apply extra optimizations (+89% performance)

Catalog list refactoring

---

Dockerfile
package-lock.json
package.json
src/sdg/conf/base.py
src/sdg/js/components/filter.js
src/sdg/organisaties/tests/test_overheden.py
src/sdg/organisaties/views/catalogi.py
src/sdg/producten/forms.py
src/sdg/producten/models/localized.py
src/sdg/producten/models/managers.py
src/sdg/producten/models/mixins.py
src/sdg/producten/models/product.py
src/sdg/producten/tests/test_views.py
src/sdg/producten/types.py
src/sdg/scss/components/_filter.scss
src/sdg/scss/components/_flags.scss
src/sdg/scss/components/_index.scss
src/sdg/scss/components/_products.scss
src/sdg/templates/core/_include/flag.html
src/sdg/templates/core/_municipality_switch.html
src/sdg/templates/organisaties/_include/catalog_filter.html
src/sdg/templates/organisaties/_include/product_catalog.html
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/edit.html
src/sdg/utils/templatetags/utils.py
webpack.config.js

Fixes #201
_______
**Changes**
- Fix bug with missing reference translation
- Add and integrate flag-icon-css
- Create and implement `Language` type 
- Allow editing product target groups
- Add target group filter

Flags and group filters

---

.github/workflows/ci.yml
src/openapi.yaml
src/sdg/api/filters/filtersets.py
src/sdg/api/serializers/core.py
src/sdg/api/serializers/organisaties.py
src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_api.py
src/sdg/api/tests/test_filters.py
src/sdg/api/views/core.py

Fixes #274
_______
**Changes**
- Update serializers
- Add organization filters
- Add/update tests
- Update catalog queryset (+95%)
- Added the following tests:
```
test_filter_organisatie_owms_identifier
test_filter_organisatie_owms_pref_label
```

API convenience features

---

src/sdg/js/components/calendar.js
src/sdg/js/components/form.js
src/sdg/js/components/general.js
src/sdg/js/components/index.js
src/sdg/producten/constants.py
src/sdg/producten/forms.py
src/sdg/producten/models/localized.py
src/sdg/producten/models/product.py
src/sdg/producten/tests/test_views.py
src/sdg/producten/views/product.py
src/sdg/scss/components/_button.scss
src/sdg/scss/components/_calendar.scss
src/sdg/scss/components/_form-actions.scss
src/sdg/scss/components/_tabs.scss
src/sdg/templates/core/base.html
src/sdg/templates/forms/table_row.html
src/sdg/templates/master.html
src/sdg/templates/producten/_include/detail_warnings.html
src/sdg/templates/producten/_include/edit_warnings.html
src/sdg/templates/producten/_include/product_status.html
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/edit.html

Fixes #219
_______
**Changes**
- Updated UX/design for product pages
- Optimize product detail (+51%)

Update UX/design for product pages

---

src/sdg/accounts/forms.py
src/sdg/accounts/views/auth.py
src/sdg/urls.py

Fixes #237
_______
**Changes**
- Override 2FA's login view with custom form validation
- Changed validation message to `Voer een juist e-mailadres en wachtwoord in` (#162)

Customize 2FA login form

---

package-lock.json
package.json
src/sdg/js/components/ckeditor.js

Fixes #209
_______
**Changes**
- Add table to markdown editor

Add table to markdown editor

---

src/sdg/organisaties/views/catalogi.py

Fixes #288
_______
**Changes**
- Update logic for municipalities without automatic catalogs

Update logic for municipalities without automatic catalogs

---

src/openapi.yaml
src/sdg/api/filters/filtersets.py

Fixes #30
_______
**Changes**
- Allow `__gte` filtering for publication date

Update publication date filter

---

src/sdg/producten/models/product.py
src/sdg/producten/templatetags/producten.py
src/sdg/producten/utils.py
src/sdg/producten/views/product.py
src/sdg/templates/core/_include/flag.html
src/sdg/templates/organisaties/_include/catalog_filter.html
src/sdg/templates/organisaties/_include/product_catalog.html
src/sdg/templates/producten/_include/flag.html
src/sdg/templates/producten/_include/icon.html
src/sdg/templates/producten/_include/product_icon.html
src/sdg/utils/templatetags/utils.py

**Changes**
- Hotfix for product url kwargs and redirect (after architectural changes) 
- Refactored icon to show tooltip on all pages

Hotfix for product URL and redirect

---

src/sdg/js/components/general.js
src/sdg/js/components/notifications.js
src/sdg/producten/models/mixins.py
src/sdg/producten/types.py
src/sdg/scss/components/_footer.scss
src/sdg/scss/components/_general.scss
src/sdg/scss/components/_header.scss
src/sdg/scss/components/_products.scss
src/sdg/scss/components/_tabs.scss
src/sdg/scss/screen.scss
src/sdg/templates/core/index.html
src/sdg/templates/forms/table_row.html
src/sdg/templates/producten/_include/detail_warnings.html
src/sdg/templates/producten/_include/edit_warnings.html

**Changes**
- Added small tweaks and UX changes

Small tweaks and UX refinement

---

src/sdg/scss/components/_header.scss

Fixes #302
Solution cherry picked from #193 (unmerged).
_______
**Changes**
- Adjust user panel for longer usernames

Adjust user panel for longer usernames

---

src/sdg/accounts/forms.py
src/sdg/templates/two_factor/core/login.html

Fixes #237
_______
**Changes**
- Fixed bug by simplifying the custom 2fa form validation

Fix bug with 2fa form validation

---

src/openapi.yaml
src/sdg/producten/forms.py
src/sdg/producten/models/product.py
src/sdg/scss/components/_revision-list.scss
src/sdg/scss/components/_tabs.scss
src/sdg/templates/forms/widgets/checkbox_option.html
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/edit.html

Fixes #295
_______
**Changes**
- Update product pages and styling

Update product pages and styling

---

src/openapi.yaml
src/sdg/api/tests/test_api.py
src/sdg/api/urls.py
src/sdg/api/views/producten.py

Fixes #300
_______
**Changes**
- Add API endpoint for concept products.
- Add test for concept endpoint.

Concept API endpoint

---

src/sdg/js/components/notifications.js
src/sdg/scss/components/_diff.scss
src/sdg/scss/components/_dynamic.scss
src/sdg/scss/components/_form-actions.scss
src/sdg/scss/components/_form.scss
src/sdg/scss/components/_login.scss
src/sdg/scss/components/_notifications.scss
src/sdg/scss/components/_revision-list.scss
src/sdg/scss/components/_tabs.scss
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/edit.html

**Changes**
- Added fadeout to notifications
- Fix diff color with display button
- More consistent margin/padding
- Removed duplicate doelgroep in edit form
- Update revision list styling
- Update labeled url field

Minor UX updates

---

src/sdg/accounts/admin.py
src/sdg/organisaties/forms.py
src/sdg/producten/tests/constants.py

Cherry picked from #190
Fixes #314 
_______
**Changes**
- Set form's initial country to `Nederland`

Set initial country to Nederland

---

src/sdg/accounts/admin.py
src/sdg/scss/components/_filter.scss
src/sdg/templates/organisaties/_include/catalog_filter.html

Fixes #315
_______
**Changes**
- Added labels to filter icons

Add labels to filter icons

---

src/sdg/accounts/admin.py
src/sdg/conf/base.py
src/sdg/core/models/logius.py
src/sdg/core/tests/models/test_logius.py

Fixes #316
_______
**Changes**
- Update `get_active_fields` for SDG codes

Update `get_active_fields` for SDG codes

---

src/sdg/js/components/catalog/filter.js

Fixes #317
_______
**Changes**
- Fix group filters

Fix group filters

---

src/sdg/templates/forms/table_field.html
src/sdg/templates/producten/edit.html

Fixes #319
_______
**Changes**
-  Hide diff for certain fields

Hide diff for link fields

---

src/sdg/templates/organisaties/_include/product_catalog.html
src/sdg/templates/producten/_include/product_icon.html

Fixes #327
_______
**Changes**
- Update status icons for reference catalogs

Update status icons for reference catalogs

---

src/sdg/js/components/diff.js
src/sdg/js/components/product/reference.js
src/sdg/producten/views/product.py
src/sdg/scss/components/_reference.scss
src/sdg/scss/components/_tabs.scss

Fixes #322
_______
**Changes**
- Added small updates to diff design/UX

Small updates to diff design/UX

---

src/sdg/scss/components/_form.scss

Fixes #325
_______
**Changes**
- Make validation errors red

Make validation errors red

---

src/sdg/templates/account/password_reset.html
src/sdg/templates/account/password_reset_done.html
src/sdg/templates/account/password_reset_from_key.html
src/sdg/templates/account/password_reset_from_key_done.html

Fixes #342
_______
**Changes**
- Fix and update password reset templates

Password reset fixes

---

src/sdg/producten/tests/test_views.py
src/sdg/templates/producten/_include/detail_warnings.html
src/sdg/templates/producten/_include/edit_warnings.html
src/sdg/templates/producten/_include/schedule_to_concept_warning.html

Small textual changes.
Fixed a bug with the date in a notification and made the unit test functional.

Updated information messages

---

src/sdg/accounts/admin.py
src/sdg/core/events.py
src/sdg/producten/tests/constants.py

Fixes #312
_______
**Changes**
- Add success/error message for admin user creation

User creation feedback message

---

src/openapi.yaml
src/sdg/api/serializers/organisaties.py
src/sdg/api/serializers/producten.py

Fixes #260
_______
**Changes**
- Use nested serializer for locations

Display location data directly (API)

---

package-lock.json
package.json
src/sdg/js/components/index.js
src/sdg/js/components/tooltip.js
src/sdg/scss/components/_index.scss
src/sdg/scss/components/_tooltip.scss
src/sdg/templates/account/base.html
src/sdg/templates/admin/base_site.html
src/sdg/templates/core/base_home.html
src/sdg/templates/master.html
src/sdg/templates/producten/base.html

Fixes #347
_______
**Changes**
- Added tippy.js dependency
- Add improved tooltip to info icons

Add improved tooltip to info icons

---

src/sdg/templates/forms/table_row.html
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/update.html

Fixes #360
_______
**Changes**
- Urlify generic product title using `landelijke_link`.
- Urlify labeded urls.

Urlify specific product fields

---

src/sdg/conf/base.py
src/sdg/scss/components/_ckeditor.scss
src/sdg/scss/components/_index.scss
src/sdg/scss/components/_tabs.scss
src/sdg/scss/screen.scss
src/sdg/templates/producten/detail.html

Fixes #358
_______
**Changes**
- Fix markdown rendering issues

Fix markdown rendering issues

---

src/sdg/js/components/catalog/expand.js
src/sdg/js/components/catalog/filter.js

Fixes #318
_______
**Changes**
- Display the state of the expand icon

Display the state of the expand icon

---

src/sdg/producten/models/product.py
src/sdg/scss/components/_revision-list.scss
src/sdg/templates/producten/detail.html

Fixes #345
_______
**Changes**
- Avoid displaying translation tabs if there is no active version

Avoid displaying translation tabs if there is no active version

---

src/sdg/js/components/diff.js
src/sdg/organisaties/views/catalogi.py
src/sdg/scss/components/_form.scss
src/sdg/scss/components/_reference.scss
src/sdg/scss/components/_tabs.scss
src/sdg/templates/forms/table_field.html
src/sdg/templates/organisaties/_include/catalog_filter.html

Fixes #372
_______
**Changes**
- Adjust category and product sorting
- Rename filter to search
- Apply changes to diff

Apply changes to the CMS

---

src/sdg/producten/models/product.py
src/sdg/producten/types.py
src/sdg/scss/components/_products.scss
src/sdg/templates/organisaties/_include/product_catalog.html
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/update.html

Fixes #293
_______
**Changes**
- Hide all language flags

Hide all language flags

---

src/sdg/js/components/dynamic_array.js
src/sdg/js/components/formset.js
src/sdg/js/components/markdown.js
src/sdg/producten/models/product.py
src/sdg/producten/tests/test_views.py
src/sdg/producten/views/product.py
src/sdg/scss/components/_checkbox.scss
src/sdg/scss/components/_form.scss
src/sdg/templates/producten/_include/availability_warnings.html
src/sdg/templates/producten/_include/detail_warnings.html
src/sdg/templates/producten/_include/edit_warnings.html
src/sdg/templates/producten/detail.html
src/sdg/templates/producten/update.html

Fixes #381
_______
**Changes**
- Apply final touches

Final touches

---

src/sdg/producten/views/product.py
src/sdg/templates/producten/_include/detail_warnings.html

**Changes**
- Fix lazy evaluation of queryset date
- Remove template comment

Fix lazy evaluation of queryset date

---

src/openapi.yaml
src/sdg/api/serializers/organisaties.py
src/sdg/api/serializers/producten.py

**Changes**
- Adjust location serializers

Adjust location serializers

---

src/sdg/templates/forms/table_field.html
src/sdg/templates/producten/update.html

Fixes #389
**Changes**
- Update the diff button for link fields

Update the diff button for link fields

---

src/sdg/conf/base.py

Otherwise it doesn't work properly.

Handle SUBPATH for markdownx

---

bin/celery_beat.sh
bin/celery_worker.sh
package-lock.json
package.json
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes #385
_______
**Changes**
- Update vulnerable python dependencies

Update npm and python dependencies

---

src/sdg/producten/models/mixins.py
src/sdg/producten/tests/test_views.py
src/sdg/producten/types.py
src/sdg/templates/forms/table_row.html
src/sdg/templates/producten/_include/field_info.html
src/sdg/templates/producten/detail.html

Fixes #370
_______
**Changes**
- Remove reference text functionality

Remove reference text functionality

---

src/sdg/templates/producten/update.html

Fixes #491
_______
**Changes**
removed review link in update.html

Removed review link

---

src/sdg/js/components/generic.js

Fixes #498 
_______
**Changes**
Made the generic.js form const queryselector more specific

Fixed bug that blocked the custom tooltips for reference products 

---

src/sdg/scss/components/_header.scss

Alternative to: https://github.com/maykinmedia/sdg-invoervoorziening/pull/517, different color scheme.

Alternative dropdown menu version.

---

src/sdg/components/templatetags/localized_form.py
src/sdg/core/models/managers.py
src/sdg/organisaties/tests/test_overheden.py
src/sdg/organisaties/views/catalogi.py
src/sdg/producten/management/commands/update_catalogs.py
src/sdg/producten/models/localized.py
src/sdg/producten/models/managers.py
src/sdg/producten/models/product.py
src/sdg/producten/templatetags/producten.py
src/sdg/producten/tests/test_update_catalogs.py
src/sdg/producten/views/product.py
src/sdg/templates/producten/update.html

This was needed to accomodate the new design, and pre-emptively fill each catalog.

Replaced ad-hoc product creation with bulk action.

---

src/sdg/organisaties/views/catalogi.py

Fixes #487 
_______
**Changes**
Added doelgroep column.

Added doelgroep column to list view

---

src/sdg/conf/base.py
src/sdg/templates/core/email/invitation.html

Changed invite mail texts

---

src/sdg/js/components/generic.js

Fixes a clash with various form instances.

:ambulance: - Fix issue with form clash for generic form.

---

src/sdg/templates/producten/update.html

Fixes #549
_______
**Changes**
changed global language selector's title from: "De waarde voor deze taal is aangepast" to "Let op dat je beide talen aanpast"

:speech_balloon: [#549] changed global language selector's title

---

src/sdg/templates/producten/update.html

Fixes #554 
_______
**Changes**
changed the subheading class text.

:pencil2: [#554] changed the subheading class text.

---

src/sdg/components/templates/components/localized_form/localized_form.html

Fixes #552 
_______
**Changes**
changed the title of the buttons.

:pencil2: [#552] changed the title of the buttons.

---

src/sdg/producten/models/mixins.py
src/sdg/producten/views/product.py
src/sdg/templates/forms/table_row.html
src/sdg/templates/producten/_include/field_info.html
src/sdg/templates/producten/update.html
src/sdg/utils/templatetags/utils.py

Fixes #532
_______
**Changes**
Added function retrieve the en and nl genrieke gegevens
Changed the update.html and the table_row.html to display the different language text for generieke gegevens

:sparkles: [#532] nederlands en engels tonen voor generieke teksten

---

src/sdg/producten/models/mixins.py
src/sdg/producten/templatetags/producten.py
src/sdg/producten/views/product.py
src/sdg/scss/mocks/_kvk.scss
src/sdg/static/js/mocks/kvk.js
src/sdg/templates/mocks/kvk.html
src/sdg/templates/producten/update.html

Fixes #418 
_______
**Changes**
changed the layout and the data on the preview page
made the markdown on the preview page the same as the markdown on the edit page
added 2 links to the preview page one for a published item and one for a concept item

:lipstick: [#418] preview page

---

src/sdg/producten/views/product.py
src/sdg/scss/mocks/_kvk.scss
src/sdg/templates/mocks/kvk.html

More changes to preview

---

src/sdg/scss/components/_toolbar.scss

Fixes #541
_______
**Changes**
Added media querys for when backdrop-filter does and does not exist

:bug:[541] added media querys to apply background blur

---

src/sdg/components/templates/components/localized_form/localized_form.html
src/sdg/js/components/form/abstract/reference_text_component.js
src/sdg/scss/components/_tabs.scss

Fixes #534
_______
**Changes**
Added stye elements to make the markdown better visable on the edit page.

:lipstick: [534] made the markdown content more viewable in the update page

---

src/sdg/components/templates/components/localized_form/localized_form.html
src/sdg/core/forms/widgets.py
src/sdg/templates/forms/widgets/dynamic_array.html

Fixes #519
_______
**Changes**
added optional lockable variable for the dynamic array widget

:sparkles:[519] removed lockable toggle for the location page

---

src/sdg/producten/admin/product.py
src/sdg/producten/models/product.py
src/sdg/templates/core/base.html
src/sdg/templates/producten/update.html

Fixes #588
_______
**Changes**
removed if statement in __str__ added ordering in admin page
added text referentie on over page

:sparkels:[588] removed if statement from __str__

---

src/sdg/js/components/form/form_diff_button.js
src/sdg/js/components/form/reference_diff_button.js

Fixes #585
_______
**Changes**
Added showdown on getDiffHtml() function.
Added more class elements to get the correct html styling.

:lipstick:[585] added showdown to render the diff elements as markdown

---

src/sdg/js/components/bevoegde_organisaties.js
src/sdg/js/components/choices.js
src/sdg/templates/organisaties/_prefix/organisatie_formset.html
src/sdg/templates/organisaties/bevoegde_organisaties.html

Fixes #600
_______
**Changes**
Added missing dom elements for the locale overheid organisatie
added check in the bevoegde_organisaties.js to see if object has a checkbox
updated the organisatie_formset to add hidden and delete field

:bug:[600]added dom elements so the js can detect all organisations

---

src/sdg/js/components/markdown.js

Fixes #609
_______
**Changes**
Removed code that prevented people to use softbreaks

:bug:[609] removed code that was blocking softbreaks

---

src/sdg/core/models/logius.py
src/sdg/organisaties/models.py

Fixes #581
_______
**Changes**
changed str of lokale overheid and organisation to display end date

:sparkles:[581] added end date to organistation str

---

src/sdg/producten/tests/test_update_catalogs.py

Fixes #593
_______
**Changes**
Wrote test cases for the update_catalogs command

:white_check_mark:[593] changed empty tests to working tests

---

src/sdg/producten/views/product.py

Fixes #608
_______
**Changes**
added decentrale procedure link to the _get_specifieke_taal_producten

:art:[608] added decentrale procedure link to the preview page

---

src/sdg/conf/base.py
src/sdg/templates/mocks/kvk.html
src/sdg/templates/producten/_include/field_info.html

Fixes #648
_______
**Changes**
Removed linebreakbr tags
Added br to the white_list markdownify tags in the settings

:art:[648] removed unwanted whitespacing

---

src/sdg/templates/producten/update.html

Fixes #450
_______
**Changes**
Added hidden disabled button to restruct the ability of submitting the form with enter

:sparkles:[450] disabled submition on enter

---

src/sdg/producten/forms.py

Fixes #606
_______
**Changes**
Changed the standard publicatie date to be of today unless the previous selected date is in the future.

:sparkles:[606] changed standard publicatie date to today or future date

---

src/sdg/producten/admin/product.py

Fixes #628
_______
**Changes**
Changed the AdminVersion Product query to only show products that are linked to the locations catalog on the change page

:bug:[628] changed the product query for the admin version change page

---

src/sdg/organisaties/views/catalogi.py
src/sdg/scss/views/organisaties/_organisaties-productenlijst-list.scss

Issues#20220621

---

src/sdg/js/components/ckeditor.js
src/sdg/scss/components/_ckeditor.scss
src/sdg/templates/mocks/kvk.html

Fixes #551
_______
**Changes**
Added indent and outdent to the ckeditor.js

:sparkles:[551] added indent and outdent to the ckeditor

---

src/sdg/scss/components/_tabs.scss

Fixes #685
_______
**Changes**
Changed the way we style the li in the _tabs.scss

:bug: [#685] changed li styling for _tabs

---

src/sdg/api/_assets/SDG-invoervoorziening.postman_collection.json

Fixes #669
_______
**Changes**
created a postman collection for the current api calls

:sparkles: [#669] created a postman collection for the current api calls

---

build/paths.js
src/sdg/api/urls.py
src/sdg/scss/api.scss
src/sdg/scss/views/_index.scss
src/sdg/scss/views/api/_button.scss
src/sdg/scss/views/api/_container.scss
src/sdg/scss/views/api/_footer.scss
src/sdg/scss/views/api/_index.scss
src/sdg/scss/views/api/_link.scss
src/sdg/scss/views/api/_nav.scss
src/sdg/scss/views/api/_space.scss
src/sdg/scss/views/api/_title.scss
src/sdg/static/js/mocks/api.js
src/sdg/templates/api/index.html
src/sdg/urls.py
webpack.config.js

Fixes #667
_______
**Changes**
Added a landing page for the API and added styling for it

:sparkles: [#667] created a landing page for the api.

---

src/openapi.yaml
src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_producten.py

Fixes #681
_______
**Changes**
Changed doelgroep to be a required field
Added doelgroep to select a generic product
added tests to test a non valid doelgroep

:art: [#681] made doelgroep a required field in the api

---

src/sdg/conf/base.py

Fixes #690
_______
**Changes**
Changed variable from boolean to config instance

:art: [#690] made SDG_CMS_ENDABLED into a environment setting

---

src/sdg/scss/views/_index.scss

Fixes #702
_______
**Changes**
Removed the mentioning of api in the cms css file

:bug: [#702] removed api button styling in default css file

---

src/sdg/scss/components/_form.scss

Fixes #637
_______
**Changes**
Changed colour of the i tag in the update.html when text has been edited

:lipstick: [#637] changed colour of the i tag in the update.html

---

src/sdg/scss/mocks/_kvk.scss
src/sdg/templates/mocks/kvk.html

Fixes #[Issue number]
_______
**Changes**
Changed the way we outline the preview page.
Hide fields completely that are not filled out.

:art: [#621] improved outlineing of preview page

---

src/sdg/producten/forms.py
src/sdg/producten/views/product.py
src/sdg/templates/producten/update.html

Fixes #672
_______
**Changes**
Added doelgroep to the product update page
added doelgroep to the duplicated product valt onder choices

:sparkles: [#672] added doelgroep to the duplicate product choices

---

src/openapi.yaml
src/sdg/api/serializers/organisaties.py
src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_producten.py
src/sdg/organisaties/tests/factories/overheid.py

Fixes #678
_______
**Changes**
refactor bevoegdeOrg in producten api to now be linked by name
Added and updated api tests

:recycle: [#678] refactor bevoegdeOrg

---

src/sdg/accounts/admin.py
src/sdg/accounts/views/password_reset.py
src/sdg/static/js/admin/resend_invite.js
src/sdg/urls.py

Fixes #651
_______
**Changes**
Added button that resend inventation mail

:sparkles: [#651] added button to resend mail

---

src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_producten.py

Fixes #723 
_______
**Changes**
Added code that transformed verwijzing_links from dict to list in the product api serializer
Added product api test to see if the translations get saved properly when fully filled out

:bug: [#723] fixed bug that crashed product api

---

src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_product_versies.py
src/sdg/api/tests/test_producten.py
src/sdg/core/tests/factories/logius.py
src/sdg/organisaties/tests/factories/overheid.py
src/sdg/producten/tests/test_views.py

Fixes #724
_______
**Changes**
- added correct version control based on date in the producten api
- added tests to test if the version gets handled correctly

:sparkles: [#724] added correct version controll based on date

---

src/sdg/api/serializers/producten.py

Fixes #732 
_______
**Changes**
Added better check for the bevoegdeOrganisatie

:bug: [#732] fixed bug that would crash api if bevoegde_org is empty dict

---

src/openapi.yaml
src/sdg/api/_assets/SDG-invoervoorziening.postman_collection.json
src/sdg/api/serializers/organisaties.py
src/sdg/api/tests/test_organisaties.py
src/sdg/api/views/organisaties.py
src/sdg/api/views/producten.py

Fixes #738
_______
**Changes**
- Added update API call for the organisatie contact details
- Added separate serializer for the organisatie update
- Added unit tests for the organisatie update call
- Added the new api call in the postman collection

:sparkles: [#738] added a organisatie update api call for the contact details

---

src/sdg/accounts/admin.py
src/sdg/static/js/admin/resend_invite.js

Fixes #742 
_______
**Changes**
- Added quotes around subpath in button's function
- Added extra alert option when the request fails

:bug: [#742] added quotes around subpath

---

src/sdg/producten/admin/product.py

Fixes #716
_______
**Changes**
- Changed function to return first item of annotated item publication_dates

:art: [#716] annotated publication_dates for the product admin page

---

src/openapi.yaml
src/sdg/api/serializers/organisaties.py
src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_filters.py
src/sdg/api/tests/test_locaties.py
src/sdg/api/tests/test_producten.py
src/sdg/api/views/producten.py
src/sdg/conf/api.py

Fixes #736
_______
**Changes**
Removed identify based on labels.
Made URI fields required.

:sparkles: [#736] remove identify based on label

---

src/sdg/accounts/admin.py
src/sdg/core/admin/logius.py

Fixes #399 
_______
**Changes**
- Updated upn filter
- Added Sorting and filtering for TOTP devices page

:sparkles: [#399] added search and filter on otp devices

---

src/sdg/api/serializers/organisaties.py
src/sdg/api/serializers/producten.py
src/sdg/producten/models/validators.py

Fixes #741 
_______
**Changes**
- translated all custom drf messages to be in Dutch.
- made the markdown validation error messages more readable.
Merge #740 this ticket to reduce the chance of merge conflicts

:art: [#741] Changed custom drf messages to be dutch

---

src/sdg/producten/management/commands/update_catalogs.py
src/sdg/producten/models/localized.py
src/sdg/producten/models/product.py
src/sdg/producten/tests/test_update_catalogs.py

Fixes #714
_______
**Changes**
- Added command flag to update only empty english texts
- Added test

Command flag: Update empty english texts

---

src/sdg/templates/producten/_include/edit_warnings.html

Fixed showing date in message for future publications

---

CHANGELOG.rst
README.rst
src/openapi.yaml
src/sdg/__init__.py
src/sdg/conf/api.py

Release 1.4.0 with combined IPO and VNG changes.

Release 1.4.0

---

src/sdg/accounts/models.py

Fixes #770
_______
**Changes**
- Added ordering for user model. TOTPDevice needs user ordering for proper sorting.

Sorting user in TOTP admin page (#770)

---

src/sdg/components/templates/components/localized_form/localized_form.html
src/sdg/components/templates/components/toggle/toggle.html
src/sdg/js/components/form/global_language_switch.js
src/sdg/js/components/form/index.js
src/sdg/js/components/form/language_switch.js
src/sdg/js/components/form/toggle.js
src/sdg/scss/components/_index.scss
src/sdg/scss/components/_toolbox.scss
src/sdg/templates/forms/table_field.html
src/sdg/templates/forms/widgets/dynamic_array.html
src/sdg/templates/producten/update.html

Fixes #617
_______
**Changes**
- Added sticky toolbox to product page

Add sticky toolbox (#617)

---

src/sdg/producten/views/product.py

Fixes #747
_______
**Changes**
- Minor updates to dynamic texts

Update product-valt-onder text

---

src/sdg/services/management/commands/import_data_from_services.py
src/sdg/services/tests/data/example_api_response.json
src/sdg/services/tests/test_management_commands.py

Fixes #671
_______
**Changes**
- Changed param to "upnUri" when loading data from services

Update data loading from services (#671)

---

src/sdg/producten/forms.py
src/sdg/producten/views/product.py

Fixes #622
_______
Added decentrale procedure label to the cms

:sparkless: [#662] added decentrale procedure label to cms

---

src/sdg/accounts/forms.py
src/sdg/organisaties/tests/test_invitation.py
src/sdg/organisaties/views/invitation.py
src/sdg/templates/organisaties/invitation/accept.html

Fixes #785
_______
**Changes**
- Ensured proper validation for invitation password
- Added test for invitation password validation

Ensure proper password policy (#785)

---

src/sdg/accounts/views/auth.py

Fixes vng-taiga (#40)
_______
**Changes**
- Ensure django-axes is enabled and works with 2FA

vng-taiga #40

---

src/sdg/components/templates/components/nonlocalized_form/nonlocalized_form.html
src/sdg/templates/producten/update.html

Fixes #799
_______
**Changes**
- Added missing lock icon

Add missing lock icon

---

src/sdg/accounts/views/auth.py

**Changes**
- Cache the form instance to access the correct form.is_valid()
Workaround for django-two-factor-auth + axes.

Fix bug with 2FA token step

---

docs/functioneel_beheer.md
package-lock.json
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/sdg/organisaties/views/roles.py
src/sdg/producten/admin/filters.py
src/sdg/producten/admin/product.py
src/sdg/producten/management/commands/autofill.py
src/sdg/templates/core/email/invitation.html
src/sdg/templates/organisaties/invitation/create.html
src/sdg/templates/organisaties/notificaties/list.html
src/sdg/templates/organisaties/roles/_user.html
src/sdg/templates/organisaties/roles/list.html

* Add documentation for statusses
* Add filter for SDG products
* Update deps

Sprint 9 feedback

---

src/sdg/producten/models/managers.py
src/sdg/producten/models/product.py
src/sdg/producten/views/product.py
src/sdg/scss/screen.scss
src/sdg/templates/producten/update.html

Fixes #792
_______
**Changes**
- Display information area in product viewd

Information area in product view (#792)

---

src/sdg/api/tests/test_producten.py
src/sdg/api/views/producten.py
src/sdg/producten/models/managers.py

Fixes #809
_______
**Changes**
- Excluded products with certain generic product status from the API
- Added test

Exclude deleted products from the API

---

src/sdg/api/tests/test_catalogi.py
src/sdg/api/tests/test_organisaties.py
src/sdg/api/tests/test_producten.py
src/sdg/api/views/core.py
src/sdg/api/views/organisaties.py
src/sdg/api/views/producten.py
src/sdg/core/models/managers.py
src/sdg/core/tests/factories/logius.py
src/sdg/organisaties/managers.py
src/sdg/producten/models/managers.py

Fixes #408
_______
**Changes**
- Ensured API data is filtered for active organizations
- Added tests

API access (active organizations only)

---

src/sdg/organisaties/admin.py

Fixes #801
_______
**Changes**
- Added organisation and address field in the admin location list view.
- Added organisation filter to the location page.

:sparkles: [#801] added extra admin fields

---

src/sdg/api/views/producten.py
src/sdg/core/constants/product.py
src/sdg/organisaties/tests/test_overheden.py
src/sdg/organisaties/views/catalogi.py
src/sdg/producten/models/managers.py
src/sdg/producten/tests/factories/product.py
src/sdg/producten/tests/test_views.py
src/sdg/producten/views/product.py

Fixes #819
_______
**Changes**
- Update queryset for cms catalog and product views
- Added tests

Exclude products based on generic status (CMS)

---

README.rst
src/sdg/conf/base.py
src/sdg/core/constants/logius.py
src/sdg/core/tasks.py

Initial start on Waterschappen.

:tada: Introduced waterschappen/waterauthorities

---

src/openapi.yaml
src/sdg/conf/api.py

And, how returns are communicated.

Added docs about supporting tables.

---

src/sdg/producten/forms.py

Fixes #815
_______
**Changes**
- Update `product_valt_onder` queryset
- Fix postfix for empty doelgroep.d

Fix postfix + update queryset

---

src/sdg/organisaties/views/catalogi.py

Fixes #837
_______
**Changes**
- Apply small adjustment to header ordering

Adjust header ordering

---

src/sdg/templates/mocks/kvk.html

Fixes #793
_______
**Changes**
- Added formulier to preview links
- Added noopener/noreferrer 
- Formated tel/email

Adjust product preview links

---

src/sdg/conf/locale/en/LC_MESSAGES/django.po
src/sdg/conf/locale/nl/LC_MESSAGES/django.po
src/sdg/producten/forms.py
src/sdg/producten/models/product.py
src/sdg/producten/tests/test_product.py
src/sdg/producten/views/product.py
src/sdg/scss/components/_notifications.scss
src/sdg/utils/validators.py

Fixes #856
_______
**Changes**
- Small performance improvements to product update.
- Added validators for placeholders
- Implement validators for placeholders
- Added tests for specific, concept + reference

Product text with placeholder validation

---

src/sdg/organisaties/forms.py
src/sdg/organisaties/tests/test_bevoegde_organisaties.py
src/sdg/organisaties/views/bevoegde_organisaties.py

Fixes #868
_______
**Changes**
- Fixed bug related to authorized organizations form
- Added tests

Fix authorized organizations update form

---

.github/workflows/ci.yml
src/sdg/core/tasks.py

**Changes**
Mentioned in: https://github.com/maykinmedia/sdg-invoervoorziening/pull/829#issuecomment-1329225115
- Changed org type setting to singular form

Hotfix for org type setting

---

Dockerfile
src/sdg/conf/locale/en/LC_MESSAGES/django.po
src/sdg/conf/locale/nl/LC_MESSAGES/django.po
src/sdg/core/models/base.py
src/sdg/core/models/config.py
src/sdg/core/models/localized_config.py
src/sdg/core/models/mixins.py
src/sdg/core/types.py
src/sdg/core/utils.py
src/sdg/producten/models/mixins.py
src/sdg/producten/templatetags/producten.py
src/sdg/producten/types.py
src/sdg/templates/forms/table_row.html
src/sdg/templates/mocks/kvk.html
src/sdg/templates/producten/update.html

Fixes #838
_______
**Changes**
- Translate field labels
- Add missing translations
- Handle configurable fields
- Ensure docker compiles translations

Fix preview label translations

---

src/sdg/api/authentication.py
src/sdg/api/tests/test_auth.py

Fixes #861
_______
**Changes**
- Added exception for case where API token instance is not found

Display error for invalid API token

---

src/sdg/api/serializers/producten.py
src/sdg/api/views/producten.py

Fixes #875, #878
_______
**Changes**
- Added try except on the retrieving from the locations based on name
- Changed order of priority when retrieving bevoegde organisations

:bug: [#875] fix 500 request when entering invalid location name

---

src/openapi.yaml
src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_producten.py

Fixes #866
_______
**Changes**
- Updated serializer to inherit correctly and fix nested serializer
- Added regression test

Fix missing data for product serializer

---

src/openapi.yaml
src/sdg/api/serializers/organisaties.py
src/sdg/api/serializers/producten.py
src/sdg/api/views/organisaties.py

Fixes #879
_______
**Changes**
- Added uuid for locations to the read_only
- fixed bug where certain location fields wouldnt show as read_only for product call
- changed the way we check if the user has the right to make create calls for this organisation

:art: [#879] added uuid as read_only field for locations

---

src/sdg/producten/forms.py
src/sdg/producten/tests/test_product.py
src/sdg/producten/utils.py
src/sdg/producten/views/product.py
src/sdg/utils/validators.py

Fixes #841
Fixes #843
_______
**Changes**
- Extract placeholder mappings into a function
- Added tests
- Refactor/simplify code
- Debug + pass tests

Clean/validate dynamically generated field text 

---

src/sdg/utils/tests/test_validators.py
src/sdg/utils/validators.py

Fixes #886
_______
**Changes**
- Added regex lookahead for placeholder validator
- Added tests for placeholder validator

Update placeholder validator pattern

---

src/sdg/producten/management/commands/clean_products.py
src/sdg/producten/tests/commands/test_clean_products.py
src/sdg/producten/utils.py

Fixes #844
_______
**Changes**
- Add command for cleaning products
- Added tests

Add command for cleaning products

---

src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_producten.py

Fixes #824
_______
**Changes**
- Added logic to LocalizedProductSerializer
- Added tests

Empty certain explanation based on product logic

---

src/sdg/producten/tests/test_product.py
src/sdg/producten/views/product.py
src/sdg/templates/producten/update.html
src/sdg/utils/templatetags/utils.py

Fixes #895
_______
**Changes**
- Added regression tests
- Cherry picked previous logic + small adjustment

Add preview concept link

---

src/sdg/conf/base.py
src/sdg/templates/account/base.html

Fixes sentry#91
_______
**Changes**
- Removed starter backend
- Fix obscured sentry report by dynamic staticfile variable

Sentry 91 bugfix

---

.gitignore
src/sdg/producten/management/commands/dump_products.py

**Changes**
- Added dump commant for products

Add dump commant for products

---

src/sdg/conf/base.py

Fixes taiga/hwh-sdg#44
_______
**Changes**
- Update field order

Update field order

---

src/sdg/core/views/mixins.py
src/sdg/js/components/bevoegde_organisaties.js
src/sdg/js/components/dynamic_array.js
src/sdg/organisaties/views/bevoegde_organisaties.py
src/sdg/organisaties/views/notificaties.py
src/sdg/producten/views/product.py
src/sdg/templates/core/base.html
src/sdg/templates/organisaties/bevoegde_organisaties.html
src/sdg/templates/organisaties/notificaties/list.html

Fixes #905
_______
**Changes**
- Applied small JS bug fixes
- Updated code for breadcrumbs

Fixes for bevoegde organisaties

---

src/sdg/js/components/index.js
src/sdg/js/components/prevent_submit_twice.js
src/sdg/templates/producten/update.html

Fixes #924
_______
**Changes**
Added js file that prevents the submission of the form after clicking the submission button

:sparkles: [#924] added js function to prevent submiting version form twice

---

src/sdg/producten/forms.py
src/sdg/templates/producten/update.html

Fixes #931
_______
**Changes**
- added validation step to check if product_aanwezig is not "onbekent" on publication
- changed initial value of product_aanwezig if its value is None

:sparkles: [#931] added feature that doesn't allow product to be unknown when publishing

---

src/sdg/services/tests/test_client.py

**Changes**
Changed url in client_test

:bug: changed api url

---

src/sdg/scss/components/_toolbox.scss
src/sdg/templates/producten/update.html

Fixes #950
_______
**Changes**
- Added styling for toolbox translate tab
- changed concept link text

:lipstick: [#950] changed concept link text and increased size of tab

---

src/sdg/templates/organisaties/notificaties/email/notificatie.html

**Changes**
changed gb to en in notification mail

:art: changed flag to language indicator

---

src/sdg/templates/forms/widgets/labeled_category_url_field.html
src/sdg/templates/forms/widgets/labeled_url_field.html

Fixes #958
_______
**Changes**
changed the work url in the placeholder to a real example url

:lipstick: [#958] replaced placement from url to example of url

---

src/sdg/scss/components/_toolbox.scss

:bug: fix bug that would hide toolbar icons

---

src/sdg/core/models/validators.py
src/sdg/producten/forms.py
src/sdg/producten/models/validators.py

Fixes #964
_______
**Changes**
- altered none descriptive error message.
- moved decentrale_procedure_label - decentrale_procedure_link not empty validation to model

:art: [#964] improved error message text

---

src/sdg/producten/views/product.py
src/sdg/templates/mocks/kvk.html

Fixes #963
_______
**Changes**
Added label/url field in concept page

:sparkles: [#963] added label link field to preview page

---

.github/workflows/ci.yml

Removing csharp-netcore, as this generator no longer exists

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
src/sdg/__init__.py

* [#974] Updated maximum length on procedureLink to 1000 characters.
* Updated dependecies

Release 1.8.3

---

src/sdg/js/components/form/use_reference_button.js
src/sdg/producten/models/product.py

Fixes issue with the disabled button.
_______
- :sparkles: Fix issue regarding the button.

Issue disabled button - issue 1 nov

---

src/sdg/scss/components/_container.scss
src/sdg/scss/components/_footer.scss
src/sdg/scss/screen.scss
src/sdg/templates/core/base_home.html

Fixes (not linked to an issue)
_______
**Changes**
[🎨 CHANGE container--main full-size](https://github.com/maykinmedia/sdg-invoervoorziening/commit/a23e912923de0a02a8f631e2d8045c6d6d174017)
[🎨 REMOVE scrollbar-gutter css property (removes white beam)](https://github.com/maykinmedia/sdg-invoervoorziening/commit/c5f7b426cb660743d88eca948b9e6e6daddcb370)
[🎨 REFACTOR and CHANGE max width on footer](https://github.com/maykinmedia/sdg-invoervoorziening/commit/b4a4e29307ec10684c090bbcd7e682e7d2fbad0e)

Some small improvements. (NEW)

---

src/sdg/producten/management/commands/check_broken_links.py

:bug: issue with broken links checker - now validate only if a page has 404 or raised an error.
_______
**Changes**
- [🐛 issue with broken links checker](https://github.com/maykinmedia/sdg-invoervoorziening/pull/1025/commits/2dd830ab905ba4b4161bd5437e11a62d8be46e50)

:bug: ISSUE with broken links checker

---

src/sdg/js/components/form/product_valt_onder.js

Fixes found issue - occurring since last PR #1026 
_______
**Changes**
- :bug: ISSUE specific form not availible when product_available = yes

:bug: issue specific form not availible when product_available = yes

---

.github/workflows/code-quality.yml
src/sdg/producten/management/commands/check_broken_links.py

Fixes Broken link checker
_______
**Changes**
[✨ Implement link checker 2.0](https://github.com/maykinmedia/sdg-invoervoorziening/commit/56fa54e504dadf11a2a2d869b85a883d799db95b)

Issue/link checker2.0
