src/sdg/accounts/admin.py
src/sdg/producten/models/product.py
src/sdg/templates/core/base.html
src/sdg/templates/organisaties/_include/product_catalog.html
src/sdg/templates/producten/detail.html

Really minor UX stuff that I noticed while browsing:
* Changed titles to show only with capfirst instead of every word being capped.
* Changed title to show that the number refers to a version.

Small UX stuff

---

src/sdg/organisaties/views/roles.py
src/sdg/templates/organisaties/roles/list.html

Fixes #340
_______
**Changes**
- Do not display users without roles (only if a role exists for the municipality)

Role list updates

---

src/sdg/conf/base.py
src/sdg/js/components/ckeditor.js
src/sdg/producten/models/fields.py
src/sdg/producten/models/localized.py
src/sdg/producten/models/validators.py
src/sdg/scss/components/_tabs.scss

Fixes #299
This issue happens due to a lack of formatting tools (i.e. a header is needed for the table). Added in this PR.
_______
**Changes**
- Added needed formatting tools for markdown tables

Add formatting tools for markdown tables

---

src/sdg/producten/views/product.py
src/sdg/scss/components/_form.scss
src/sdg/scss/components/_notifications.scss
src/sdg/templates/producten/update.html

Fixes #369
_______
**Changes**
- Add fixed warning if the product form is invalid
Update:

Add extra warning if product form is invalid

---

src/sdg/templates/forms/table_field.html
src/sdg/templates/producten/update.html

Fixes #424
_______
**Changes**
(Reference products only)
- Removed "product_aanwezig", "product_aanwezig_toelichting", "locaties" fields entirely from edit page.

Remove certain fields for reference product edit page

---

src/sdg/js/components/abstract/component.js
src/sdg/js/components/form/abstract/form_component.js
src/sdg/js/components/form/abstract/reference_text_component.js
src/sdg/js/components/form/diff_button.js
src/sdg/js/components/form/show_reference_button.js
src/sdg/js/components/form/toggle.js
src/sdg/js/components/form/use_reference_button.js
src/sdg/scss/_settings.scss
src/sdg/scss/components/_button.scss
src/sdg/scss/components/_ckeditor.scss
src/sdg/scss/components/_dynamic.scss
src/sdg/scss/components/_highlight.scss
src/sdg/scss/components/_index.scss
src/sdg/scss/components/_tabs.scss
src/sdg/scss/components/_toggle.scss
src/sdg/scss/components/_toolbar.scss
src/sdg/templates/forms/table_field.html
src/sdg/templates/forms/widgets/dynamic_array.html
src/sdg/templates/producten/update.html

Fixes #454
_______
**Changes**
- Move "Gebruik standaardtekst" under the "Toon standaardtekst" block.
- Add label (Toon wijzigingen t.o.v. vorige versie) after eye-icon, and move the eye-function to the bottom next to "Gebruik standaard tekst".

:sparkles: #454 - Make the use of standard text use easier

---

src/sdg/organisaties/urls/__init__.py
src/sdg/templates/core/base.html

Fixes #413
_______
**Changes**
- Update front-facing text for CMS: 'catalogi' → 'productenlijst'

Rename catalogi to productenlijst

---

src/sdg/js/components/ckeditor.js

Fixes #472
_______
**Changes**
- Limit markdown editor headings to h3 and h4
-

Limit markdown editor headings

---

src/sdg/core/models/mixins.py
src/sdg/producten/forms.py
src/sdg/services/client.py
src/sdg/templates/producten/update.html

Fixes #468
_______
**Changes**
- Adjusted localized product field ordering
```
"taal",
"product_titel_decentraal",
"specifieke_tekst",
"vereisten",
"bewijs",
"procedure_beschrijving",
"kosten_en_betaalmethoden",
"uiterste_termijn",
"bezwaar_en_beroep",
"wtd_bij_geen_reactie",
"verwijzing_links",
"decentrale_procedure_link",
"product_valt_onder_toelichting",
```

Adjust localized product field ordering

---

src/sdg/scss/components/_toolbar.scss
src/sdg/templates/producten/update.html

Fixes #524
_______
**Changes**
relocated the publicatie datum error message from the left side of the field to be above the field
from:
to:

:lipstick: [#524] relocated the publicatie datum error message

---

src/sdg/templates/mocks/kvk.html

the specifieke tekst and the product title are now viable if they exist.
Fixes #579
_______
**Changes**
changed the if statement for the product_title_decentraal and specifieke_tekst so that they are rendered if they exist

:lipstick:[579] show specifieke text and title when they exist

---

src/sdg/producten/views/product.py
src/sdg/templates/producten/update.html

Fixes #547 
_______
**Changes**
- changed the layout of the Algemene Gegevens to match the "localized_form.html"
- added localized_form in the Algemene Gegevens for the fields "product_valt_onder_toelichting" and "product_aanwezig_toelichting"
- Removed "product_aanwezig_toelichting" and "product_valt_onder_toelichting"  from the "localized_form_fields" context
- changed the generic.js to triger the displayFunc for the setUpDynamicProductAanwezig when the domContent is loaded

:lipstick: [547] moved the toelichtingen fields to be under the pulldowns

---

src/sdg/producten/forms.py
src/sdg/templates/forms/table_row.html

Fixes #559 
_______
**Changes**
Added function to get the helptext for the productform
Set the default helptext to the helptext devinded in the product models

:lipstick:[559] added standard lables for algemene gegevens

---

src/sdg/producten/models/fields.py
src/sdg/producten/models/validators.py
src/sdg/producten/tests/test_models.py

Fixes #692
_______
**Changes**
Added markdown validation so that the user can't submit a form with the following elements:
- h1
- h2
- h5
- h6
- hr
- img
- code
Added unit tests to check if the markdown fields really don't allow these tags
Added unit tests to check if accepted markdown elements get though

:sparkles: [#692] added markdown validation

---

src/sdg/producten/forms.py

Fixes #650
_______
**Changes**
Removed empty label option for the bevoegde organisatie in the product.forms.ProductForm

:art: [#650] removed empty label option for bevoegde organisatie

---

src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_producten.py

Fixes #857
_______
**Changes**
- Fixed bug where api would crash on empty string as catalogus
- Added unit test to test if empty string will give you 400 page

:bug: [#857] fixed bug where the api would crash on empty string as catalogus

---

src/sdg/api/views/producten.py

Fixes #875
_______
**Changes**
- Changed ordering of organization in get_organisatie function from the ProductViewSet.
- Added extra validation if get request returns more then 2 answers to avoid http 500 requests.

:bug: [#875] fixed bug where validating key could result in 500

---

src/sdg/core/management/utils.py
src/sdg/core/tests/test_management_commands.py
src/sdg/producten/management/commands/autofill.py

Refactored the generic product generation and improved the testsuite.

:recycle: Move generic product creation to UPN

---

src/sdg/services/management/commands/import_data_from_services.py
src/sdg/services/tests/test_import_data_from_services.py

Sometimes, generic product texts disappear from the NP GT API's. Can have any number of reasons but we need to cleanup our end as well.
To prevent manually entered texts from disappearing, we only wipe the UUID to prevent duplicates in case a text was moved from one UPN to another (happened for "bodemsanering" which has 2 variants).

Clean up obsolete generic product texts

---

src/sdg/api/serializers/producten.py
src/sdg/api/tests/test_producten.py

Fixes #922
_______
**Changes**
- changed object.get call on bevoegde org model from only lokale_overheid to lokale_overheid and name.
- added validation for wrong api field in bevoegde org 
- added tests to test for different bevoegde org, none existing bevoegde org and bevoede org with wrong field

:bug: [#922] fixed bug where multiple bevoegde org would break the api

---

src/sdg/producten/forms.py
src/sdg/producten/models/product.py
src/sdg/producten/tests/factories/product.py

Fixes #929
_______
**Changes**
- Filtered out all products from product valt onder that are of different doelgroeps except if its already saved as one
- Added model validation to see if user doesn't tries to save product with product valt onder that has a different doelgroep

:art: [#929] product valt onder only contains same doelgroep

---

src/sdg/js/components/clear_form.js
src/sdg/js/components/index.js

Fixes #933
_______
**Changes**
- added js file to clear all the "SPECIFIEKE GEGEVENS" fields if "product valt onder" other product or "product aanwezig" is set to "nee"

:sparkles: [#933] clear localized fields when product valt onder or not aanwezig

---

src/sdg/producten/forms.py

Fixes #786
_______
**Changes**
If the "product_titel_decentraal" field is empty add initial value that matches generic title.

:sparkles: [#786] added function that fills in the product title with generic title if empty

---

src/sdg/producten/models/localized.py
src/sdg/producten/tests/commands/test_clean_products.py
src/sdg/producten/tests/test_product.py

Fixes #967
_______
**Changes**
remove toelichting on model level when not false

:bug: [#967] on model level clear product_aanwezig_toelichting if setting is not false

---

src/sdg/scss/components/_ckeditor.scss

Fixes indent styling for ckeditor bullet list

:bug: fixed bullet list alignment issue

---

src/sdg/scss/components/_ckeditor.scss

Fixed bug where focusing ckeditor field made toolbar sticky would merge with global page toolbar.

:bug: changed sticky ckeditor panel to static

---

src/sdg/organisaties/views/catalogi.py
src/sdg/producten/views/product.py
src/sdg/scss/components/_colors.scss
src/sdg/scss/components/_select.scss
src/sdg/scss/views/organisaties/_organisaties-productenlijst-list.scss
src/sdg/templates/core/base.html
src/sdg/templates/organisaties/catalogi/list.html
src/sdg/templates/producten/update.html

Fixes #995
_______
**Changes**
- 🔥 REMOVE informatiegebied colom on the productlist page
- ✨ UPDATE the name of the product on the detail page (also in the breadcrumbs)
- 🔥REMOVE introduction on the productlist page

:sparkles: 995 Implement feebdack on productlist page

---

src/sdg/producten/models/product.py
src/sdg/producten/tests/test_product.py
src/sdg/producten/views/product.py
src/sdg/templates/producten/_include/productversie.html

Fixes #989 
_______
- 💄 CHANGE the appearance of the `productversie.html`
- 🗃️ CHANGE the stored `new_version.bewerkte_velden` so that only the specific form field are shown inside the `productversie.html`.
- 🩹 CHANGE the `ProductVersie` order property from `versie` to `gewijzigd_op`, to make sure the order is based on the chronical timeline instead of the version.

#989 fix sorted product history.

---

src/sdg/templates/organisaties/invitation/create.html
src/sdg/templates/organisaties/roles/delete.html
src/sdg/templates/organisaties/update.html

Fixes #999
_______
- ♻️ REFACTOR some incorrect nested semantics

:recycle: [#999] REFACTOR some incorrect nested semantics

---

src/sdg/producten/management/commands/send_email_to_users_about_doordrukken.py
src/sdg/producten/management/commands/send_monthly_broken_links_report.py
src/sdg/templates/producten/_include/doordruk_warning.html
src/sdg/templates/producten/email/email_broken_links.html
src/sdg/templates/producten/email/email_inform_about_doordrukken.html
src/sdg/templates/producten/update.html

Fixes `Sprint Feedback`
_______
**Changes**
- [✨ ADD bar to the update form with only cancel button.](https://github.com/maykinmedia/sdg-invoervoorziening/commit/ba7b9e98eac87bab521238e9f7fc3991fb9c3099)

:sparkles: ADD bar to the  update form with only cancel button.

---

src/sdg/producten/management/commands/send_monthly_broken_links_report.py

Fixes wrong added encoded slash.
_______
**Changes**
- [🐛 REMOVE wrong added encoded slash on broken links email.](https://github.com/maykinmedia/sdg-invoervoorziening/commit/a27193ef4051f8205182f783fa47e65c76a2b82f)

:bug: REMOVE wrong added encoded slash on broken links email.

---

src/sdg/js/components/form/abstract/clarification_field_component.js
src/sdg/js/components/form/product_available.js
src/sdg/js/components/form/product_valt_onder.js

🐛  Collapse specific form onMount if product is not available or f…alls under other product.
_______
**Changes**
- 🐛  Collapse specific form onMount if product is not available or f…alls under other product.
- 🩹 Remove logic that a reference form specific data can't be collapsed.

:bug: Collapse specific form onMount.

---

src/sdg/producten/management/commands/send_monthly_broken_links_report.py

Users that were inactive still received an email for broken links.

Fixed mailing inactive users
